Supporting publishable and validate directory (#7)
* skip_terraform_validation

* use ftf

* cache checkcov with python gha

* Revert "cache checkcov with python gha" (#5)

* Ensure requirements.txt is present to prevent setup-python failure (#6)

* Update action.yml

* added publishable flag

* added support for validate

* removed true from check only

---------

Co-authored-by: unni-facets <krishnanunni.menon@facets.cloud>
Co-authored-by: Jayant <jayant.sharma@facets.cloud>
Co-authored-by: Jayant <39442192+RoguedBear@users.noreply.github.com>

diff --git a/module-preview-action/action.yml b/module-preview-action/action.yml
--- a/module-preview-action/action.yml
+++ b/module-preview-action/action.yml
@@ -20,6 +20,22 @@ inputs:
     description: "Run the action for all modules in repo"
     required: false
     default: "false"
+  skip-terraform-validation:
+    description: "Skip the Terraform Validate step"
+    required: false
+    default: "false"
+  auto-create-intent:
+    description: "Automatically create intent if not exists"
+    required: false
+    default: "false"
+  publish:
+    description: "Publish the module"
+    required: false
+    default: "false"
+  publishable:
+    description: "Whether the modules registered in preview mode are publishable or not. This is not required if publish is set to true."
+    required: false
+    default: "false"
 
 runs:
   using: "composite"
@@ -29,6 +45,16 @@ runs:
       with:
         fetch-depth: 0
 
+    # This step is needed since setup-python fails if it doesnt detect either of these two files
+    - if: hashFiles('**/requirements.txt', '**/pyproject.toml') == ''
+      shell: bash
+      run: |
+          touch ./requirements.txt
+
+    - uses: actions/setup-python@v5
+      with:
+        python-version: "3.12"
+        cache: "pip"
 
     - name: Install Dependencies (Facets, Terraform, Checkov)
       shell: bash
@@ -36,11 +62,11 @@ runs:
         sudo apt-get install -y python3 python3-pip curl unzip jq git
         curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
         unzip terraform.zip && mv terraform /usr/local/bin/ && rm terraform.zip
-        pip install checkov
+        pip install git+https://github.com/Facets-cloud/module-development-cli.git
 
     - name: Identify All Facets Modules (All Modules)
       if: inputs.all-modules == 'true'
-      id: dry_run_dirs
+      id: all_dirs
       shell: bash
       run: |
         echo "🚀 Step: Identify All Facets Modules (All Modules)"
@@ -101,36 +127,6 @@ runs:
         echo "dirs=$FACETS_DIRS" >> "$GITHUB_ENV"
         echo "✅ Step complete."
 
-
-
-    - name: Run Terraform Formatting Check (Fail on Incorrect Formatting)
-      if: env.dirs != ''
-      shell: bash
-      run: |
-        for dir in $dirs; do
-          echo "🔍 Checking Terraform formatting in $dir"
-          terraform fmt -recursive -check "$dir" || (echo "❌ Terraform formatting issues found in $dir. Run 'terraform fmt' locally." && exit 1)
-        done
-
-    - name: Run Terraform Validate
-      if: env.dirs != ''
-      shell: bash
-      run: |
-        for dir in $dirs; do
-          echo "✅ Validating Terraform in $dir"
-          terraform  -chdir="$dir" init -backend=false 
-          terraform -chdir="$dir" validate 
-        done
-
-    - name: Run Checkov Security Scan
-      if: env.dirs != ''
-      shell: bash
-      run: |
-        for dir in $dirs; do
-          echo "🔍 Running Checkov security scan in $dir"
-          checkov -d "$dir" --quiet --hard-fail-on HIGH,CRITICAL --framework terraform,kubernetes --output cli
-        done
-
     - name: Get Git Info
       if: env.dirs != '' && inputs.dry-run != 'true'
       id: git_info
@@ -148,19 +144,33 @@ runs:
         echo "🔍 Git Commit ID: $COMMIT_ID"
         echo "🔍 Git URL: $GIT_URL"
 
-    - name: Preview Facets Module
+    - name: FTF Login
+      if: env.dirs != '' && inputs.dry-run != 'true'
+      shell: bash
+      run: |
+        echo "✅ Login to CP using ftf"
+        ftf login -c "${{ inputs.control_plane_url }}" -u "${{ inputs.username }}" -t "${{ inputs.token }}" -p default
+
+    - name: FTF Validate Directory
+      if: env.dirs != '' && inputs.dry-run == 'true'
+      shell: bash
+      run: |
+        for dir in $dirs; do
+          if [[ -f "$dir/facets.yaml" ]]; then
+            echo "⏳ Validating Facets Module in directory $dir"
+            ftf validate-directory $dir --check-only --skip-terraform-validation "${{ inputs.skip-terraform-validation }}"
+            echo "✔️ Facets Module in directory $dir validated successfully."
+          fi
+        done
+
+
+    - name: Register Facets Module
       if: env.dirs != '' && inputs.dry-run != 'true'
       shell: bash
       run: |
         for dir in $dirs; do
           if [[ -f "$dir/facets.yaml" ]]; then
-            echo "🔍 Registering Facets module for preview in $dir..."
-            curl -s https://facets-cloud.github.io/facets-schemas/scripts/module_register.sh | bash -s -- \
-              -c "${{ inputs.control_plane_url }}" \
-              -u "${{ inputs.username }}" \
-              -t "${{ inputs.token }}" \
-              -p "$dir" -a \
-              -g "${{ env.git_url }}" \
-              -r "${{ env.commit_id }}"
+            echo "🔍 Registering Facets module for $([ \"${{ inputs.publish }}\" = \"true\" ] && echo publishing || echo preview) in $dir..."
+            ftf preview-module $dir -a "${{ inputs.auto-create-intent }}" -r "${{ env.commit_id }}" -g "${{ env.git_url }}" --publish "${{ inputs.publish }}"  --publishable "${{ inputs.publishable }}" --profile default --skip-terraform-validation "${{ inputs.skip-terraform-validation }}"
           fi
         done
